name: xeus-cling
channels:
  - conda-forge
dependencies:
  - xeus-cling
  - xeus-python
  - matplotlib-base
  - notebook
  - pip
  - pip:
    - nbgitpuller
    - RISE
    - jupyter_contrib_nbextensions
