name: docs

on:
  push

jobs:
  build_docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up  python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: install dependencies
      run: |
        pip install -r ./docs/requirements.txt
        sudo apt-get install -y wkhtmltopdf

    - name: create slides 
      run: |
        jupyter nbconvert --to slides --embed-images --template reveal --output-dir docs/source/_static "notebooks/*.ipynb"
    
    - name: Convert notebooks to PDF
      run: |
        for html_file in docs/source/_static/*.html; do
            # Create the PDF file name from the HTML file name
            pdf_file="${html_file%.html}.pdf"
            
            # Convert HTML to PDF using wkhtmltopdf (or replace with google-chrome for headless conversion)
            wkhtmltopdf --orientation landscape "$html_file" "$pdf_file"
            
          done

    - name: Convert README.md to README.rst
      uses: docker://pandoc/core:latest
      with:
        args: --from=markdown --to=rst --output=docs/source/README.rst README.md

    - name: Post-process README.rst for substitution issues
      run: |
        # Fix common malformed substitution issues caused by pandoc conversion
          sed -i 's/i mag e3/|image3|/g' docs/source/README.rst
          sed -i 's/i mag e6/|image6|/g' docs/source/README.rst
          sed -i 's/im age 12/|image12|/g' docs/source/README.rst
          sed -i 's/im age 15/|image15|/g' docs/source/README.rst
          sed -i 's/im age 18/|image18|/g' docs/source/README.rst
          sed -i 's/im age 21/|image21|/g' docs/source/README.rst
    
    - name: build docs
      run: |
        sphinx-build -W -b html docs/source docs/build -j auto

    - name: deploy docs only if it is pushed to main
      uses: peaceiris/actions-gh-pages@v3
      # publish every time there's a push to the 2024 branch
      if: ${{ github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build
        force_orphan: true
